# see https://symfony.com/doc/current/reference/configuration/framework.html
# config/packages/framework.yaml
framework:
    secret: '%env(APP_SECRET)%'

    csrf_protection: true

    session:
        # La session sera démarrée uniquement si nécessaire
        handler_id: null
        cookie_secure: true
        cookie_httponly: true
        cookie_samesite: lax

    form: true

    # Optionnel : ESI et fragments si utilisés
    # esi: true
    # fragments: true


when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file 