framework:
    secret: '%env(APP_SECRET)%'

    csrf_protection: true

    session:
        cookie_secure: true
        cookie_httponly: true
        cookie_samesite: lax
        gc_maxlifetime: 1800
        cookie_lifetime: 0

    form: true


when@test:
    framework:
        secret: 'test_secret'    # Peut être différent (simple string)
        test: true

when@prod:
    framework:
        http_method_override: false
        ide: null
        test: false
        router:
            strict_requirements: null
        cache:
            app: cache.adapter.filesystem
            system: cache.adapter.system

when@dev:
    framework:
        router:
            strict_requirements: true
        profiler:
            collect: true
