# config/packages/security.yaml
security:
    password_hashers:
        App\Entity\User: 'auto'

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            lazy: true
            provider: app_user_provider

            form_login:
                login_path: account_login
                check_path: account_login
                default_target_path: account

            logout:
                path: account_logout
                target: account

            remember_me:
                secret: '%kernel.secret%'
                lifetime: 1800
                path: /
                secure: true
                httponly: true
                samesite: lax
                always_remember_me: false

    access_control:
        - { path: ^/account$, roles: ROLE_USER }
